sudo: false
language: python
python: 3.6
install: pip install tox-travis
script: tox

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: doc/build
  fqdn: doc.mergify.io
  on:
    branch: master
    python: 3.6
