dist: trusty
sudo: false
language: python
python: 2.7
install:
      - pip install tox
script:
      - tox
env:
      - TOXENV=pep8
      - TOXENV=py27
      - TOXENV=py35
      - TOXENV=docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
