dist: trusty
sudo: required
language: generic
env:
      - TOXENV=pep8
      - TOXENV=py36-cover
      - TOXENV=docs

install:
      - sudo add-apt-repository -y ppa:deadsnakes/ppa ; sudo apt-get -qq update ; sudo apt-get install -y python3.6 python3.6-dev;
      - sudo pip install -U pip tox coveralls
script:
      - tox
after_success:
    - [ "$TOXENV" == "py36-cover" ] && coveralls

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: doc/build
  fqdn: doc.mergify.io
  on:
    branch: master
    condition: $TOXENV = docs
